"""H4 BOT/Toll: Generate SQL INSERT for toll_stations from extracted CSV.
Inserts as is_active=FALSE (admin enables after geocoding).
Skips stations whose name already exists.
"""
from pathlib import Path
import csv

CSV = Path(r"D:\Beer HL\bhl-oms\scripts\data\toll_stations_extracted.csv")
SQL = Path(r"D:\Beer HL\bhl-oms\migrations\039_toll_stations_extra.up.sql")

rows = []
with CSV.open(encoding="utf-8-sig") as f:
    for r in csv.DictReader(f):
        rows.append(r)

# Build INSERT
sql_lines = [
    "-- Migration 039: Import 44 toll stations extracted from VETC 2022-2023 invoices",
    "-- Source: D:\\Xu ly Data cho BHL\\output\\01_VETC_BOT_Consolidated_22_23.xlsx",
    "-- Generated by scripts/build_toll_sql.py",
    "-- Status: is_active=FALSE until lat/lng geocoded by ops team",
    "",
    "BEGIN;",
    "",
]

for r in rows:
    name = r["station_name"].replace("'", "''")
    fee_avg = float(r["fee_truck_3t5_vnd"])
    fee_8t = float(r["fee_truck_8t_vnd"])
    fee_15t = float(r["fee_truck_15t_vnd"])
    notes = f"Auto-extracted from VETC {r['transactions_2022_2023']} txns 2022-2023; needs geocoding"
    sql_lines.append(
        f"INSERT INTO toll_stations (station_name, latitude, longitude, "
        f"fee_l1, fee_l2, fee_l3, fee_l4, fee_l5, is_active, notes) "
        f"SELECT '{name}', 0, 0, "
        f"{fee_avg/2:.0f}, {fee_avg:.0f}, {fee_8t:.0f}, {fee_15t:.0f}, {fee_15t*1.3:.0f}, "
        f"FALSE, '{notes}' "
        f"WHERE NOT EXISTS (SELECT 1 FROM toll_stations WHERE station_name = '{name}');"
    )

sql_lines.extend(["", "COMMIT;", ""])
SQL.write_text("\n".join(sql_lines), encoding="utf-8")
print(f"wrote {SQL} ({len(rows)} rows)")
