@echo off
REM Restart VRP Solver + auto-run compare test
cd /d "d:\Beer HL\bhl-oms"
echo Restarting VRP Solver (avg-cost-matrix fix)...
docker compose restart vrp
echo Waiting 12s for Python to initialize...
timeout /t 12 /nobreak >nul
echo Checking VRP health...
curl -sf http://localhost:8090/health
echo.
echo Running compare test (takes ~3 min)...
powershell -NoProfile -ExecutionPolicy Bypass -File ".\tmp_run_compare.ps1"
pause
