-- Reverse migration
DROP TABLE IF EXISTS receivable_ledger CASCADE;
DROP TABLE IF EXISTS trip_stops CASCADE;
DROP TABLE IF EXISTS trips CASCADE;
DROP TABLE IF EXISTS stock_quants CASCADE;
DROP TABLE IF EXISTS lots CASCADE;
DROP TABLE IF EXISTS shipments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS sales_orders CASCADE;
DROP TABLE IF EXISTS delivery_routes CASCADE;
DROP TABLE IF EXISTS drivers CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS warehouses CASCADE;
DROP TABLE IF EXISTS credit_limits CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS ledger_type;
DROP TYPE IF EXISTS vehicle_type;
DROP TYPE IF EXISTS stop_status;
DROP TYPE IF EXISTS trip_status;
DROP TYPE IF EXISTS shipment_status;
DROP TYPE IF EXISTS order_status;
