import { test, expect, Page } from '@playwright/test'

// E2E-1: Dispatcher tạo đơn hàng → verify order trong DB qua API
// Luồng: Login → Tạo đơn → Xác nhận order tồn tại

const BASE = 'http://localhost:3000'
const API = 'http://localhost:8080/v1'

async function loginAsDispatcher(page: Page): Promise<string> {
  // Gọi API để lấy token (nhanh hơn login qua UI)
  const res = await page.request.post(`${API}/auth/login`, {
    data: { username: 'dispatcher01', password: 'demo123' },
  })
  expect(res.status()).toBe(200)
  const body = await res.json()
  return body.data.access_token
}

test.describe('E2E-1: Dispatcher tạo đơn', () => {
  let token: string

  test.beforeEach(async ({ page }) => {
    token = await loginAsDispatcher(page)
  })

  test('dispatcher login và load trang tạo đơn', async ({ page }) => {
    // Set token vào localStorage
    await page.goto(`${BASE}/login`)
    await page.evaluate((t) => localStorage.setItem('access_token', t), token)

    // Navigate tới form tạo đơn
    await page.goto(`${BASE}/dashboard/orders/new`)
    await expect(page).not.toHaveURL(/login/)
    await expect(page.locator('h1, h2').first()).toBeVisible()
  })

  test('form tạo đơn render đầy đủ fields', async ({ page }) => {
    await page.goto(`${BASE}/login`)
    await page.evaluate((t) => localStorage.setItem('access_token', t), token)
    await page.goto(`${BASE}/dashboard/orders/new`)

    // Kiểm tra các field bắt buộc
    await expect(page.locator('[data-testid="customer-select"], select, input').first()).toBeVisible()

    // Trang không blank và không có lỗi JS blocking render
    const errors: string[] = []
    page.on('console', (msg) => {
      if (msg.type() === 'error') errors.push(msg.text())
    })
    await page.waitForTimeout(2000)
    const blockingErrors = errors.filter(e =>
      e.includes('TypeError') || e.includes('Cannot read') || e.includes('is not a function')
    )
    expect(blockingErrors).toHaveLength(0)
  })

  test('gọi API tạo đơn trực tiếp → order được tạo trong DB', async ({ page }) => {
    // Lấy danh sách customer và warehouse trước
    const customersRes = await page.request.get(`${API}/customers`, {
      headers: { Authorization: `Bearer ${token}` },
    })
    const customers = await customersRes.json()
    const warehousesRes = await page.request.get(`${API}/warehouses`, {
      headers: { Authorization: `Bearer ${token}` },
    })
    const warehouses = await warehousesRes.json()
    const productsRes = await page.request.get(`${API}/products`, {
      headers: { Authorization: `Bearer ${token}` },
    })
    const products = await productsRes.json()

    // Skip nếu không có test data
    if (!customers.data?.length || !warehouses.data?.length || !products.data?.length) {
      test.skip()
      return
    }

    const tomorrow = new Date()
    tomorrow.setDate(tomorrow.getDate() + 1)
    const deliveryDate = tomorrow.toISOString().split('T')[0]

    const createRes = await page.request.post(`${API}/orders`, {
      headers: { Authorization: `Bearer ${token}` },
      data: {
        customer_id: customers.data[0].id,
        warehouse_id: warehouses.data[0].id,
        delivery_date: deliveryDate,
        is_urgent: false,
        notes: '[E2E TEST] Auto-generated by Playwright — delete after test',
        items: [{ product_id: products.data[0].id, quantity: 1 }],
      },
    })

    // 201 = created, 400 = validation/business rule (không phải lỗi E2E)
    expect([200, 201, 400, 422]).toContain(createRes.status())

    if (createRes.status() === 201 || createRes.status() === 200) {
      const order = await createRes.json()
      expect(order.data).toHaveProperty('id')
      expect(order.data).toHaveProperty('status')
      expect(order.data.id).toBeTruthy()

      // Verify order tồn tại trong DB qua GET
      const getRes = await page.request.get(`${API}/orders/${order.data.id}`, {
        headers: { Authorization: `Bearer ${token}` },
      })
      expect(getRes.status()).toBe(200)
      const fetched = await getRes.json()
      expect(fetched.data.id).toBe(order.data.id)
    }
  })
})
